CREATE TABLE "metadata_edits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "metadata_edits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"batch_id" text NOT NULL,
	"item_id" integer,
	"track_id" integer,
	"field" text NOT NULL,
	"old_value" text,
	"new_value" text,
	"user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "metadata_edit_target" CHECK (("metadata_edits"."item_id" IS NULL) <> ("metadata_edits"."track_id" IS NULL))
);
--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN "locked_fields" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "tracks" ADD COLUMN "locked_fields" text[] DEFAULT '{}'::text[] NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_edits" ADD CONSTRAINT "metadata_edits_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metadata_edits" ADD CONSTRAINT "metadata_edits_track_id_tracks_id_fk" FOREIGN KEY ("track_id") REFERENCES "public"."tracks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metadata_edits" ADD CONSTRAINT "metadata_edits_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "metadata_edit_batch" ON "metadata_edits" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "metadata_edit_item" ON "metadata_edits" USING btree ("item_id");